/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.cm.tsi.projetointegrador.gui;

import br.edu.utfpr.cm.tsi.projetointegrador.turma.CadastroTurmas;

/**
 *
 * @author Daniel
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnCadastros = new javax.swing.JMenu();
        rbmiAluno = new javax.swing.JRadioButtonMenuItem();
        rmbiTurma = new javax.swing.JRadioButtonMenuItem();
        rbmiFuncionario = new javax.swing.JRadioButtonMenuItem();
        rbmiPiscina = new javax.swing.JRadioButtonMenuItem();
        rbmiMensalidade = new javax.swing.JRadioButtonMenuItem();
        mnMovimentos = new javax.swing.JMenu();
        rbmiMatricula = new javax.swing.JRadioButtonMenuItem();
        rmbiFrequencia = new javax.swing.JRadioButtonMenuItem();
        mnConsultas = new javax.swing.JMenu();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem6 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem7 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem8 = new javax.swing.JRadioButtonMenuItem();
        mnSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        mnCadastros.setText("Cadastros");

        rbmiAluno.setSelected(true);
        rbmiAluno.setText("Aluno");
        rbmiAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        rbmiAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmiAlunoActionPerformed(evt);
            }
        });
        mnCadastros.add(rbmiAluno);

        rmbiTurma.setSelected(true);
        rmbiTurma.setText("Turma");
        rmbiTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Group.png"))); // NOI18N
        rmbiTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmbiTurmaActionPerformed(evt);
            }
        });
        mnCadastros.add(rmbiTurma);

        rbmiFuncionario.setSelected(true);
        rbmiFuncionario.setText("Funcionario");
        mnCadastros.add(rbmiFuncionario);

        rbmiPiscina.setSelected(true);
        rbmiPiscina.setText("Piscina");
        mnCadastros.add(rbmiPiscina);

        rbmiMensalidade.setSelected(true);
        rbmiMensalidade.setText("Mensalidade");
        mnCadastros.add(rbmiMensalidade);

        jMenuBar1.add(mnCadastros);

        mnMovimentos.setText("Movimentos");

        rbmiMatricula.setSelected(true);
        rbmiMatricula.setText("Matricula");
        mnMovimentos.add(rbmiMatricula);

        rmbiFrequencia.setSelected(true);
        rmbiFrequencia.setText("Frequencia");
        mnMovimentos.add(rmbiFrequencia);

        jMenuBar1.add(mnMovimentos);

        mnConsultas.setText("Consultas");

        jRadioButtonMenuItem5.setSelected(true);
        jRadioButtonMenuItem5.setText("Alunos");
        mnConsultas.add(jRadioButtonMenuItem5);

        jRadioButtonMenuItem6.setSelected(true);
        jRadioButtonMenuItem6.setText("Turmas");
        mnConsultas.add(jRadioButtonMenuItem6);

        jRadioButtonMenuItem7.setSelected(true);
        jRadioButtonMenuItem7.setText("Funcionarios");
        mnConsultas.add(jRadioButtonMenuItem7);

        jRadioButtonMenuItem8.setSelected(true);
        jRadioButtonMenuItem8.setText("Piscinas");
        mnConsultas.add(jRadioButtonMenuItem8);

        jMenuBar1.add(mnConsultas);

        mnSair.setText("Sair");
        mnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnSairMouseClicked(evt);
            }
        });
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbmiAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmiAlunoActionPerformed
    }//GEN-LAST:event_rbmiAlunoActionPerformed

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed
    }//GEN-LAST:event_mnSairActionPerformed

    private void mnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_mnSairMouseClicked

    private void rmbiTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmbiTurmaActionPerformed
        new CadastroTurmas().setVisible(true);
    }//GEN-LAST:event_rmbiTurmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem8;
    private javax.swing.JMenu mnCadastros;
    private javax.swing.JMenu mnConsultas;
    private javax.swing.JMenu mnMovimentos;
    private javax.swing.JMenu mnSair;
    private javax.swing.JRadioButtonMenuItem rbmiAluno;
    private javax.swing.JRadioButtonMenuItem rbmiFuncionario;
    private javax.swing.JRadioButtonMenuItem rbmiMatricula;
    private javax.swing.JRadioButtonMenuItem rbmiMensalidade;
    private javax.swing.JRadioButtonMenuItem rbmiPiscina;
    private javax.swing.JRadioButtonMenuItem rmbiFrequencia;
    private javax.swing.JRadioButtonMenuItem rmbiTurma;
    // End of variables declaration//GEN-END:variables
}
